apiVersion: apps/v1
kind: Deployment
metadata:
  name: agaia-files
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agaia-files
  template:
    metadata:
      labels:
        app: agaia-files
    spec:
      containers:
        - name: app
          image: lubomirhadziev/agaia-files:1.16.0
          resources:
            requests:
              memory: "150Mi"
            limits:
              memory: "350Mi"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agaia-files-hpa
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agaia-files
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 280
---
apiVersion: v1
kind: Service
metadata:
  name: agaia-files
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "files.agaia.life"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "042d191e-392f-4b56-9daf-7514326c9f7c"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "files.agaia.life"
spec:
  selector:
    app: agaia-files
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer