apiVersion: apps/v1
kind: Deployment
metadata:
  name: agaia-files
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agaia-files
  template:
    metadata:
      labels:
        app: agaia-files
    spec:
      containers:
        - name: app
          image: lubomirhadziev/agaia-files:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 1
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: agaia-recipes
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "images.agaia.life"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "48b9ea55-a2b5-4cae-9626-7932bd01508e"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "images.agaia.life"
spec:
  selector:
    app: agaia-recipes
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080

    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer