apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakExTURFeQpNREUwTlRkYUZ3MDBNakExTURFeU1ERTBOVGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQ29VWW10UGdHaWY1Mk5SMW5PeVVzeE85Sko0cmliMlM4OCtBclBROVpucTNsZkhMRQp4VjZBdEFnU1IwMXZlRTNpMzlsRjkwc0pocFkzVlg3SnNBdEtzb213V0N0cUZpejJVcndqSU1LMzFFbi9CeERDCkI2MkI0Y3N4ZEd3N1M3SStWYURsdE9XeDhVU2t0dUZYempBTWhIZ0dzQ3Z4Ky9VZG9oN1loQmFXaGxtQzFxMXoKZERmejVHcW01NHNGSk5WNzBRNUxoek42dXkyTkRCekxmNVRDck1KN1U5bXNHdk5DRHo0dHBiUFo4TFFHSGYySwpHV0g3RXFPNzc5TXdSbDM0d0tJdDRZbXhFMzVjTUh2djFPdURoV0duNVlKK1RVQTJPTTczZW5jZEdhbEdtMlYxCnlOWE1zdVQ4M2tNZHhzQnMvdng2bTgxQ09xb0FuZGkvVWdvVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJmVWo2MU9scStydCtHN085cgpOMEF6alk5UzB6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsS0VHZmVHcWczSFV5Z2RXY2NBUlcvZktEM013Ci9KRWVvYWFNWFBheTRSZWJxZEFrWjRlOWF2RDRsTEo3RnVDSy9HQ01pK2hxQnBkWTg2VUpxWTdSbnFxQkh1MmQKV0FwSmIzTVgxYnpibEs1bGVKN1M2UVc0anpiMHFSYkdjWExIYUFuRVBBUVdIN0RadnBrT2laMDJrQWc0UWMxVQozTFF0M2JEUWdKV1lZL3VqRTE1T3h5aWg0d29XMEVvSkd1dGZzbUxVViswQmtycHNGSzF0WFo3QlFGVUhWeHpNCmwwSU54SWxPT1gzTWdyb1B6RmNhdVhESWN0QTFIUEE3Q2RCS1FnRmZ1N25IRXROUkNEZ01PazllMUhPOU9QYlIKVmJLV2RZTmlwYUFoczl0SEVRNk13YjBYWXRxa2MxcE9mY2FqRnB0akwxQzlVZUo3VEk5WWR4Y3R0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://08a3d678-c6ee-42e2-b222-a2b8b2876d0d.k8s.ondigitalocean.com
    name: do-fra1-k8s-1-22-8-do-1-fra1-1651436019717
contexts:
  - context:
      cluster: do-fra1-k8s-1-22-8-do-1-fra1-1651436019717
      user: do-fra1-k8s-1-22-8-do-1-fra1-1651436019717-admin
    name: do-fra1-k8s-1-22-8-do-1-fra1-1651436019717
current-context: do-fra1-k8s-1-22-8-do-1-fra1-1651436019717
kind: Config
preferences: {}
users:
  - name: do-fra1-k8s-1-22-8-do-1-fra1-1651436019717-admin
    user:
      token: dop_v1_6f7297d7f341a7c69a18c8d808bd7172e753736a36249da345d61b6137d597bd
